# Generated by Django 6.1 on 2026-08-11 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_code', models.CharField(max_length=20, unique=True)),
                ('subject_name', models.CharField(max_length=100)),
                ('semester', models.PositiveIntegerField()),
                ('credits', models.PositiveIntegerField(default=4)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='students.course')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherSubject',
            fields=[
                ('teacher_subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('academic_year', models.CharField(max_length=20)),
                ('semester', models.PositiveIntegerField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_teachers', to='students.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_subjects', to='students.teacher')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('teacher', 'subject', 'academic_year', 'semester'), name='unique_teacher_subject_assignment')],
            },
        ),
    ]
