# Generated by Django 6.1 on 2026-08-11 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('exam_id', models.AutoField(primary_key=True, serialize=False)),
                ('exam_name', models.CharField(max_length=100)),
                ('exam_type', models.CharField(choices=[('Midterm', 'Midterm'), ('Final', 'Final'), ('Practical', 'Practical')], max_length=30)),
                ('semester', models.PositiveIntegerField()),
                ('academic_year', models.CharField(max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('mark_id', models.AutoField(primary_key=True, serialize=False)),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marks_entered', to='students.teacher')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='students.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='students.subject')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'subject', 'exam'), name='unique_student_subject_exam_mark')],
            },
        ),
    ]
