# Generated by Django 6.1 on 2026-08-12 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_activitylog_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='registration_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Approved', max_length=20),
        ),
    ]
