# Generated by Django 6.1 on 2026-08-31 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_alter_userprofile_role_notice_parentprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='marked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_marked', to='students.teacher'),
        ),
        migrations.AddConstraint(
            model_name='fee',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0), ('amount_paid__gte', 0), ('amount_paid__lte', models.F('amount'))), name='valid_fee_values'),
        ),
        migrations.AddConstraint(
            model_name='mark',
            constraint=models.CheckConstraint(condition=models.Q(('marks_obtained__gte', 0), ('max_marks__gt', 0), ('marks_obtained__lte', models.F('max_marks'))), name='valid_mark_values'),
        ),
    ]
