# Generated by Django 6.1 on 2026-09-01 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_alter_attendance_marked_by_fee_valid_fee_values_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('applicant_name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('preferred_year', models.PositiveIntegerField(default=2026)),
                ('source', models.CharField(choices=[('Website', 'Website'), ('Referral', 'Referral'), ('Walk-in', 'Walk-in'), ('Social Media', 'Social Media')], default='Website', max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('New', 'New'), ('Under Review', 'Under Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='New', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='students.course')),
            ],
        ),
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('Card', 'Card'), ('Mobile Money', 'Mobile Money'), ('Other', 'Other')], default='Cash', max_length=30)),
                ('reference', models.CharField(blank=True, default='', max_length=120)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Refunded', 'Refunded')], default='Completed', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='students.fee')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grade', models.CharField(default='A', max_length=5)),
                ('remarks', models.TextField(blank=True, default='')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft')], default='Published', max_length=20)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='students.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='students.subject')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'subject', 'exam'), name='unique_student_subject_exam_result')],
            },
        ),
    ]
