# Generated by Django 6.1 on 2026-09-01 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_admissionapplication_feepayment_examresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSettings',
            fields=[
                ('settings_id', models.AutoField(primary_key=True, serialize=False)),
                ('school_name', models.CharField(default='Cloud Campus', max_length=200)),
                ('short_name', models.CharField(default='CC', max_length=50)),
                ('tagline', models.CharField(blank=True, default='Smart campus operations', max_length=200)),
                ('address', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('website', models.URLField(blank=True, default='')),
                ('academic_year', models.CharField(default='2026-2027', max_length=20)),
                ('campus_count', models.PositiveIntegerField(default=1)),
                ('subscription_plan', models.CharField(choices=[('Starter', 'Starter'), ('Growth', 'Growth'), ('Enterprise', 'Enterprise')], default='Growth', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('message', models.TextField()),
                ('category', models.CharField(choices=[('General', 'General'), ('Academic', 'Academic'), ('Exam', 'Exam'), ('Fee', 'Fee'), ('System', 'System')], default='General', max_length=25)),
                ('audience', models.CharField(choices=[('All', 'All'), ('Admin', 'Admin'), ('Teacher', 'Teacher'), ('Student', 'Student'), ('Parent', 'Parent')], default='All', max_length=20)),
                ('is_sent', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
