# Generated by Django 6.1 on 2026-09-01 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_campus_subscriptioninvoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusEvent',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('event_type', models.CharField(default='Academic', max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryBook',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=150)),
                ('category', models.CharField(default='General', max_length=60)),
                ('isbn', models.CharField(blank=True, default='', max_length=40)),
                ('total_copies', models.PositiveIntegerField(default=1)),
                ('available_copies', models.PositiveIntegerField(default=1)),
                ('rack_number', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Low Stock', 'Low Stock'), ('Archived', 'Archived')], default='Available', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TransportRoute',
            fields=[
                ('route_id', models.AutoField(primary_key=True, serialize=False)),
                ('route_name', models.CharField(max_length=120)),
                ('driver_name', models.CharField(blank=True, default='', max_length=120)),
                ('vehicle_number', models.CharField(blank=True, default='', max_length=40)),
                ('pickup_point', models.CharField(blank=True, default='', max_length=150)),
                ('drop_point', models.CharField(blank=True, default='', max_length=150)),
                ('capacity', models.PositiveIntegerField(default=40)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Paused', 'Paused'), ('Maintenance', 'Maintenance')], default='Active', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('staff_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('role', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('On Leave', 'On Leave'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff_members', to='students.department')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollRecord',
            fields=[
                ('payroll_id', models.AutoField(primary_key=True, serialize=False)),
                ('pay_period', models.CharField(max_length=20)),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Overdue', 'Overdue')], default='Pending', max_length=20)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_records', to='students.staffmember')),
            ],
        ),
        migrations.CreateModel(
            name='LibraryIssue',
            fields=[
                ('issue_id', models.AutoField(primary_key=True, serialize=False)),
                ('issued_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('returned_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Issued', 'Issued'), ('Returned', 'Returned'), ('Overdue', 'Overdue')], default='Issued', max_length=20)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='students.librarybook')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='library_issues', to='students.student')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='library_issues', to='students.staffmember')),
            ],
        ),
    ]
